apiVersion: v1
kind: Secret
metadata:
  name: hex-core-auth
type: Opaque
stringData:
  AUTH_JWKS_URL: https://keycloak.example.org/realms/ce-rise/protocol/openid-connect/certs
  AUTH_ISSUER: https://keycloak.example.org/realms/ce-rise
